SRCPREFIX = ../..
LIB=libGlutMVC.a
OBJS = \
        Glut2DController.o \
        Glut2DView.o \
        GlutController.o \
        GlutView.o \
        glut2DCommands.o \
        glutInputs.o \

all: $(LIB)

include ../../Makefile.in
