#
# SUMMON - Cygwin Makefile
#

MODULE = summon_core.dll
SRCPREFIX=src

# no glut extension for cygwin
CFLAGS=-DNOGLUTEXT

all: lib/$(MODULE)

include src/Makefile.in



# linking
LIBS = -L/lib/w32api -L/usr/local/lib -lglut32 -lopengl32 \
	-lSDL -L/lib/python2.5/config -lpython2.5


export MODULE CFLAGS LIBS


# make rule for summon module
lib/$(MODULE): src/Summon/$(MODULE)	
	cp src/Summon/$(MODULE) lib

clean: cleanall
	rm -rf lib/$(MODULE)
