SRCPREFIX = ..
LIB = libSummonSceneGraph.a
OBJS = elements.o \
       Element.o \
       Graphic.o \
       Hotspot.o \
       TextElement.o \
       Transform.o \
       TransformMatrix.o \
       ZoomClamp.o

all: $(LIB)

include ../Makefile.in
