LIB = libCommon.a
OBJS =  App.o \
        commonCommands.o \
        Matrix.o \
        Script.o \
        ScriptCommand.o \
        ScriptEngine.o \
	Terminal.o 


all: $(LIB)

include ../Makefile.in

